halstead(operators, operands, N1, N2, n1, n2, N, n, V, D, E) ::= <<

Operator:           count:
<operators.keys:{k |<k> : <operators.(k)>}; separator="\n">

Operand:            count:
<operands.keys:{k |<k> : <operands.(k)>}; separator="\n">


Halstead-Metrics:

Number of Operators         N1:         <N1>
Number of Operands          N2:         <N2>
number of unique Operators  n1:         <n1>
number of unique Operands   n2:         <n2>

Halstead-metrics:

Programmlength      N:          <N>
Vocabularysize      n:          <n>
Volume              V:          <V>
Difficulty          D:          <D>
Effort              E:          <E>
>>